version: '3.8'
services:
  mysql:
    image: mysql:8.0.37
    container_name: mysql
    restart: unless-stopped
    networks:
      - controle-de-orcamento
    environment:
      MYSQL_ROOT_PASSWORD: 6040
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=6040
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - controle-de-orcamento-data:/var/lib/mysql

  spring:
    depends_on:
      mysql:
        condition: service_healthy
    image: makinay/controle-de-orcamento-familiar:3.1
    container_name: API
    restart: unless-stopped
    networks:
      - controle-de-orcamento
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orcamento-familiar-db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 6040

  nginx:
    depends_on:
      - spring
    image: nginx:stable-alpine
    container_name: nginx
    networks:
      - controle-de-orcamento
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  controle-de-orcamento-data:

networks:
  controle-de-orcamento:
    driver: bridge