version: '3.1'
services:
  mysql:
    image: mysql:8.0.37
    container_name: mysql
    restart: unless-stopped
    networks:
      - controle-de-orcamento
    environment:
      MYSQL_ROOT_PASSWORD: 6040
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=6040
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
        - controle-de-orcamento-data:/var/lib/mysql

  spring:
    depends_on:
      mysql:
        condition: service_healthy
    image: makinay/controle-de-orcamento-familiar:1.1
    container_name: API
    restart: on-failure
    networks:
      - controle-de-orcamento
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orcamento-familiar-db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 6040

volumes:
  controle-de-orcamento-data:

networks:
  controle-de-orcamento:
    driver: bridge